./a.out 0 | tail -n 1
./a.out 1 | tail -n 1
./a.out 2 | tail -n 1
./a.out 3 | tail -n 1
./a.out 4 | tail -n 1
./a.out 5 | tail -n 1
./a.out 6 | tail -n 1
./a.out 7 | tail -n 1
echo      1	 | ./gen_input | ./a.out - | tail -n 1
echo      2	 | ./gen_input | ./a.out - | tail -n 1
echo      3	 | ./gen_input | ./a.out - | tail -n 1
echo      4	 | ./gen_input | ./a.out - | tail -n 1
echo      5	 | ./gen_input | ./a.out - | tail -n 1
echo      6	 | ./gen_input | ./a.out - | tail -n 1
echo      7	 | ./gen_input | ./a.out - | tail -n 1
echo      8	 | ./gen_input | ./a.out - | tail -n 1
echo      9	 | ./gen_input | ./a.out - | tail -n 1
echo     10	 | ./gen_input | ./a.out - | tail -n 1
echo     11	 | ./gen_input | ./a.out - | tail -n 1
echo     12	 | ./gen_input | ./a.out - | tail -n 1
echo     13	 | ./gen_input | ./a.out - | tail -n 1
echo     14	 | ./gen_input | ./a.out - | tail -n 1
echo     15	 | ./gen_input | ./a.out - | tail -n 1
echo     16	 | ./gen_input | ./a.out - | tail -n 1
echo     17	 | ./gen_input | ./a.out - | tail -n 1
echo     18	 | ./gen_input | ./a.out - | tail -n 1
echo     19	 | ./gen_input | ./a.out - | tail -n 1
echo     20	 | ./gen_input | ./a.out - | tail -n 1
echo     21	 | ./gen_input | ./a.out - | tail -n 1
echo     22	 | ./gen_input | ./a.out - | tail -n 1
echo     23	 | ./gen_input | ./a.out - | tail -n 1
echo     24	 | ./gen_input | ./a.out - | tail -n 1
echo     25	 | ./gen_input | ./a.out - | tail -n 1
echo     26	 | ./gen_input | ./a.out - | tail -n 1
echo     27	 | ./gen_input | ./a.out - | tail -n 1
echo     28	 | ./gen_input | ./a.out - | tail -n 1
echo     29	 | ./gen_input | ./a.out - | tail -n 1
echo     30	 | ./gen_input | ./a.out - | tail -n 1
echo     31	 | ./gen_input | ./a.out - | tail -n 1
echo     32	 | ./gen_input | ./a.out - | tail -n 1
echo     33	 | ./gen_input | ./a.out - | tail -n 1
echo     34	 | ./gen_input | ./a.out - | tail -n 1
echo     35	 | ./gen_input | ./a.out - | tail -n 1
echo     36	 | ./gen_input | ./a.out - | tail -n 1
echo     37	 | ./gen_input | ./a.out - | tail -n 1
echo     38	 | ./gen_input | ./a.out - | tail -n 1
echo     39	 | ./gen_input | ./a.out - | tail -n 1
echo     40	 | ./gen_input | ./a.out - | tail -n 1
echo     41	 | ./gen_input | ./a.out - | tail -n 1
echo     42	 | ./gen_input | ./a.out - | tail -n 1
echo     43	 | ./gen_input | ./a.out - | tail -n 1
echo     44	 | ./gen_input | ./a.out - | tail -n 1
echo     45	 | ./gen_input | ./a.out - | tail -n 1
echo     46	 | ./gen_input | ./a.out - | tail -n 1
echo     47	 | ./gen_input | ./a.out - | tail -n 1
echo     48	 | ./gen_input | ./a.out - | tail -n 1
echo     49	 | ./gen_input | ./a.out - | tail -n 1
echo     50	 | ./gen_input | ./a.out - | tail -n 1
echo     51	 | ./gen_input | ./a.out - | tail -n 1
echo     52	 | ./gen_input | ./a.out - | tail -n 1
echo     53	 | ./gen_input | ./a.out - | tail -n 1
echo     54	 | ./gen_input | ./a.out - | tail -n 1
echo     55	 | ./gen_input | ./a.out - | tail -n 1
echo     56	 | ./gen_input | ./a.out - | tail -n 1
echo     57	 | ./gen_input | ./a.out - | tail -n 1
echo     58	 | ./gen_input | ./a.out - | tail -n 1
echo     59	 | ./gen_input | ./a.out - | tail -n 1
echo     60	 | ./gen_input | ./a.out - | tail -n 1
echo     61	 | ./gen_input | ./a.out - | tail -n 1
echo     62	 | ./gen_input | ./a.out - | tail -n 1
echo     63	 | ./gen_input | ./a.out - | tail -n 1
echo     64	 | ./gen_input | ./a.out - | tail -n 1
echo     65	 | ./gen_input | ./a.out - | tail -n 1
echo     66	 | ./gen_input | ./a.out - | tail -n 1
echo     67	 | ./gen_input | ./a.out - | tail -n 1
echo     68	 | ./gen_input | ./a.out - | tail -n 1
echo     69	 | ./gen_input | ./a.out - | tail -n 1
echo     70	 | ./gen_input | ./a.out - | tail -n 1
echo     71	 | ./gen_input | ./a.out - | tail -n 1
echo     72	 | ./gen_input | ./a.out - | tail -n 1
echo     73	 | ./gen_input | ./a.out - | tail -n 1
echo     74	 | ./gen_input | ./a.out - | tail -n 1
echo     75	 | ./gen_input | ./a.out - | tail -n 1
echo     76	 | ./gen_input | ./a.out - | tail -n 1
echo     77	 | ./gen_input | ./a.out - | tail -n 1
echo     78	 | ./gen_input | ./a.out - | tail -n 1
echo     79	 | ./gen_input | ./a.out - | tail -n 1
echo     80	 | ./gen_input | ./a.out - | tail -n 1
echo     81	 | ./gen_input | ./a.out - | tail -n 1
echo     82	 | ./gen_input | ./a.out - | tail -n 1
echo     83	 | ./gen_input | ./a.out - | tail -n 1
echo     84	 | ./gen_input | ./a.out - | tail -n 1
echo     85	 | ./gen_input | ./a.out - | tail -n 1
echo     86	 | ./gen_input | ./a.out - | tail -n 1
echo     87	 | ./gen_input | ./a.out - | tail -n 1
echo     88	 | ./gen_input | ./a.out - | tail -n 1
echo     89	 | ./gen_input | ./a.out - | tail -n 1
echo     90	 | ./gen_input | ./a.out - | tail -n 1
echo     91	 | ./gen_input | ./a.out - | tail -n 1
echo     92	 | ./gen_input | ./a.out - | tail -n 1
echo     93	 | ./gen_input | ./a.out - | tail -n 1
echo     94	 | ./gen_input | ./a.out - | tail -n 1
echo     95	 | ./gen_input | ./a.out - | tail -n 1
echo     96	 | ./gen_input | ./a.out - | tail -n 1
echo     97	 | ./gen_input | ./a.out - | tail -n 1
echo     98	 | ./gen_input | ./a.out - | tail -n 1
echo     99	 | ./gen_input | ./a.out - | tail -n 1
echo    100	 | ./gen_input | ./a.out - | tail -n 1
